---

# Blue 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opswerks-hub-blue
  namespace: prod 
  labels:
    app: opswerks-hub
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opswerks-hub
      version: blue
  template:
    metadata:
      labels:
        app: opswerks-hub
        version: blue
    spec:
      containers:
      - name: opswerks-hub
        image: romeofrancobarro/opswerks-hub:produ
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: "lke238246-370358-3d2bde670000"


---

# Green 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opswerks-hub-green
  namespace: prod 
  labels:
    app: opswerks-hub
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opswerks-hub
      version: green
  template:
    metadata:
      labels:
        app: opswerks-hub
        version: green
    spec:
      containers:
      - name: opswerks-hub
        image: romeofrancobarro/opswerks-hub:produ
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: "lke238246-370358-3d2bde670000"


---

# Blue-Green Service
apiVersion: v1
kind: Service
metadata:
  name: opswerks-hub-service
  namespace: prod  
  labels: 
    frontend: opswerks-hub-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: opswerks-hub
    version: blue  # Active version
  ports:
  - port: 80
    targetPort: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: opswerks-hub-backend
  namespace: prod  
  labels:
    app: opswerks-hub-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: opswerks-hub-backend
  template:
    metadata:
      labels:
        app: opswerks-hub-backend
    spec:
      containers:
      - name: opswerks-hub-backend
        image: romeofrancobarro/opswerks-hub-backend:produ
        ports:
        - containerPort: 5000
        env:
        - name: NODE_ENV
          value: "production"
      nodeSelector:
        kubernetes.io/hostname: "lke238246-370358-3d2bde670000"

---

apiVersion: v1
kind: Service
metadata:
  name: opswerks-hub-backend-service
  namespace: prod
  labels: 
    backend: opswerks-hub-backend-service
spec:
  type: LoadBalancer
  selector:
    app: opswerks-hub-backend
  ports:
  - port: 5000
    targetPort: 5000

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: opswerks-hub-database
  namespace: prod  
  labels:
    app: opswerks-hub-database
spec:
  serviceName: opswerks-hub-database-service 
  replicas: 2
  selector:
    matchLabels:
      app: opswerks-hub-database
  template:
    metadata:
      labels:
        app: opswerks-hub-database
    spec:
      containers:
      - name: opswerks-hub-database
        image: cassandra:latest
        ports:
        - containerPort: 9042
        env:
        - name: CASSANDRA_SEEDS
          value: "opswerks-hub-database-0.opswerks-hub-database-service.prod.svc.cluster.local"
        - name: CASSANDRA_CLUSTER_NAME
          value: "OpsWerksHubDatabaseCluster"
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
      nodeSelector:
        kubernetes.io/hostname: "lke238246-370358-3d2bde670000"
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          memory: "8Mi"  
          cpu: "5m"      
        limits:
          memory: "16Mi"  
          cpu: "10m"

---

apiVersion: v1
kind: Service
metadata:
  name: opswerks-hub-database-service  
  namespace: prod  
spec:
  clusterIP: None  
  selector:
    app: opswerks-hub-database 
  ports:
  - port: 9042
    targetPort: 9042
